@baseUrl = https://app-osport.herokuapp.com

# 
//snkcmuclyjjrag:e460879da3dc3d10454bd6031a1f3887e8c2be23ad5911e352e49feca6da5fd8@ec2-176-34-222-188.eu-west-1.compute.amazonaws.com:5432/daindlp1mpsoct



############################## CONNEXION #############################



### Set new Password
POST {{baseUrl}}/register?token=0a8c6070-1978-448d-9317-f25dcd93a312
Content-Type: application/json

{
    "password": "member",
    "confirm": "member"
}

### Connexion
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "jcastex@gmail.com",
    "password": "owner"
}


############################## MEMBERS #############################


### Récupérer tous les adhérents
GET {{baseUrl}}/members

### Récupérer un adhérent
GET {{baseUrl}}/members/3

### Récupérer tous les Workouts d'un adhérent
GET {{baseUrl}}/workouts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWxpYmFiYUBnbWFpbC5jb20iLCJyb2xlIjoiTUVNQkVSIiwiaWF0IjoxNjE1NDc2NDQ5LCJleHAiOjE2MTU1MTI0NDl9.qpAaFFZXiLF_Foupn6gDBm99zuat5nlFe99h8Guy-iU

### Récupérer tous les healthRecords d'un adhérent
GET {{baseUrl}}/health
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWxpYmFiYUBnbWFpbC5jb20iLCJyb2xlIjoiTUVNQkVSIiwiaWF0IjoxNjE1NTQwMjM3LCJleHAiOjE2MTU1NzYyMzd9.iZb3uat6mpKcOu9o7e5qGIpPHZiWf0b90xsgjjnQrIM

### Récupérer les prochains RDV d'un member
GET {{baseUrl}}/member-next-bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM1LCJlbWFpbCI6ImFsYWludEBnbWFpbC5jb20iLCJyb2xlIjoiTUVNQkVSIiwiaWF0IjoxNjE1Mzc5MTY4LCJleHAiOjE2MTU0MTUxNjh9.LLxeSRK0kU_LeKxbknRHYlmua3Q8UYsLko3Csk3dRlk

### Ajouter un workout par un member
POST {{baseUrl}}/new-workout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWxpYmFiYUBnbWFpbC5jb20iLCJyb2xlIjoiTUVNQkVSIiwiaWF0IjoxNjE1NTcyOTE3LCJleHAiOjE2MTU2MDg5MTd9.s4y-9ShZkiz01FOxRDaXsZ9lyTWZLjBM5nRRBLkG4js

{
    "date": "2021-03-12",
    "content": "workout Ali Baba. Test 4 - Abdo 40 répétitions ",
    "weight": 70,
    "muscleMass": 30,
    "fatMass":20,
    "boneMass": 15,
    "bodyWater": 10
}

### Supprimer un workout par un member
DELETE {{baseUrl}}/delete-workout/18
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM1LCJlbWFpbCI6ImFsYWludEBnbWFpbC5jb20iLCJyb2xlIjoiTUVNQkVSIiwiaWF0IjoxNjE1NDAxNTMwLCJleHAiOjE2MTU0Mzc1MzB9.bMiPnoLxnOf84Q7Do-eh_ut2W0CCqd2yWKwV-ki6MYI

### suppression d'un user
DELETE {{baseUrl}}/users/7

### Ajouter new Member
POST {{baseUrl}}/new-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiSkNhc3RleEBnbWFpbC5jb20iLCJyb2xlIjoiT1dORVIiLCJpYXQiOjE2MTU1NDI3MDEsImV4cCI6MTYxNTU3ODcwMX0.qnWTS7xaHMUIJ62n1_UCJNOg33OH2fIVbshzyMnOYSE

{
    "firstname": "Machin",
    "lastname": "Bidulle",
    "email": "machin.bidulle@gmail.com",
    "role": "MEMBER"
}

### Ajouter new Coach (même route avec array specialities en plus)
POST {{baseUrl}}/new-user
Content-Type: application/json

{
    "firstname": "TOTO",
    "lastname": "Térieur",
    "email": "tatata@coach.com",
    "role": "COACH",
    "specialities": [2, 5]
}


############################## COACHS #############################


### Récupérer tous les coachs
GET {{baseUrl}}/coachs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiSkNhc3RleEBnbWFpbC5jb20iLCJyb2xlIjoiT1dORVIiLCJpYXQiOjE2MTU2NjM5NDcsImV4cCI6MTYxNTY5OTk0N30.6125WIM36pxSI2ieMD4hYGM76B6bJV5gHdSiHqMkO-M
### Récupérer le profil d'un coach avec les spécialités
GET {{baseUrl}}/coachs/6

### Récupérer les prochains RDV d'un coach
GET {{baseUrl}}/coach-next-bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM1LCJlbWFpbCI6ImFsYWludEBnbWFpbC5jb20iLCJyb2xlIjoiTUVNQkVSIiwiaWF0IjoxNjE1Mzc5MTY4LCJleHAiOjE2MTU0MTUxNjh9.LLxeSRK0kU_LeKxbknRHYlmua3Q8UYsLko3Csk3dRlk

### Récuperer les RDv passés d'un coach
GET {{baseUrl}}/coach-last-bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM0LCJlbWFpbCI6ImFsZXh0QGNvYWNoLmNvbSIsInJvbGUiOiJDT0FDSCIsImlhdCI6MTYxNTM5OTEzOCwiZXhwIjoxNjE1NDM1MTM4fQ.L6cu4ZTURk5gaZ6sqLynrX7IxPettaYHUX3npT8UPoE

### Ajouter new Coach (même route avec array specialities en plus)
POST {{baseUrl}}/new-user
Content-Type: application/json

{
    "firstname": "Tean",
    "lastname": "Dupont",
    "email": "Tean@edf.com",
    "role": "COACH",
    "specialities": [2, 5, 7]
}

### Ajouter new Comment
POST {{baseUrl}}/new-comment/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoiYWxleHRAY29hY2guY29tIiwicm9sZSI6IkNPQUNIIiwiaWF0IjoxNjE1NDc0OTYwLCJleHAiOjE2MTU1MTA5NjB9.Rn0ZXNXJDyuokK4xbtXWU5xxAMTUp42rVr5t4fFDG8g

{
    "content": "Bonne séance ! Keep going !!"
}

############################## COACHING #############################

### Ajouter des créneaux coaching 
POST {{baseUrl}}/new-coachings
Content-Type: application/json

{
    "date": "2021-04-15",
    "start": "09:30",
    "end": "10:00",
    "coachId": 34
}


### Récupérer coachings disponibles a une date
POST {{baseUrl}}/available-coachings
Content-Type: application/json

{
    "date": "2021-04-05"
}

### Récupérer un coaching avec le coach et le membre qui y participe
GET {{baseUrl}}/coaching/5

### suppression d'un coaching
DELETE {{baseUrl}}/coaching/5

### Réserver un coaching
POST {{baseUrl}}/book-coaching
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM1LCJlbWFpbCI6ImFsYWludEBnbWFpbC5jb20iLCJyb2xlIjoiTUVNQkVSIiwiaWF0IjoxNjE1Mzc5MTY4LCJleHAiOjE2MTU0MTUxNjh9.LLxeSRK0kU_LeKxbknRHYlmua3Q8UYsLko3Csk3dRlk

{
    "coachingId": 1
}

### Supprimer une réservation
PATCH {{baseUrl}}/bookings/3/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM1LCJlbWFpbCI6ImFsYWludEBnbWFpbC5jb20iLCJyb2xlIjoiTUVNQkVSIiwiaWF0IjoxNjE1Mzc5MTY4LCJleHAiOjE2MTU0MTUxNjh9.LLxeSRK0kU_LeKxbknRHYlmua3Q8UYsLko3Csk3dRlk

############################## SPECIALTIES #############################

### Récupérer toutes les spécialités
GET {{baseUrl}}/specialties

### Ajouter une spécialité
POST {{baseUrl}}/specialties
Content-Type: application/json

{
    "name": "Karate"
    
}

### Supprimer une spécialité
DELETE  {{baseUrl}}/specialties/15
